### ISSUE TITLE
eval.py error 

### ISSUE THREAD

**Issue by ericosmic** [EternalFeather/Transformer-in-generating-dialogue#2]
when run eval.py , it will product error like below :
![image](https://user-images.githubusercontent.com/35327931/49783762-e290fb80-fd55-11e8-8b00-0ccf34e46abc.png)
it is induce by self.inpt that pass from train.py  .   I think it need some modify in source code.

**Comment by axfv** [comment]
[https://github.com/Kyubyong/transformer/blob/master/train.py#L43](url)

**Comment by axfv** [comment]
https://github.com/Kyubyong/transformer/blob/master/train.py#L43

**Comment by zh215021** [comment]
> when run eval.py , it will product error like below :
> ![image](https://user-images.githubusercontent.com/35327931/49783762-e290fb80-fd55-11e8-8b00-0ccf34e46abc.png)
> it is induce by self.inpt that pass from train.py . I think it need some modify in source code.

have you solve this problem?

**Comment by yangjingyingGo** [comment]
I met the same question， Thanks @zh215021 ！

**Comment by ZhaoJiangJie** [comment]
same question,soveled,thx.
